src/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from .settings import IS_PRODUCTION

urlpatterns = [
    path('', include('dashboard.urls')),
    path('authentic/', include('authentic.urls')),
    path('product/', include('product.urls')),
    path('stock/', include('stock.urls')),
    path('partners/', include('partners.urls')),
    path('transactions/', include('transactions.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)


if not IS_PRODUCTION:
    urlpatterns += [
        path('gest/admin/', admin.site.urls),
    ]

transactions/urls.py
from django.urls import path
from .views import (
    purchaseTable,
    purchaseDelete,
    purchaseDetail,

    saleTable,
    saleDetail,
    saleDelete,

)
app_name = 'transactions'

urlpatterns = [
    #purchases
    path('purchases/', purchaseTable, name='purchases'),
    path('purchase/<str:pk>/', purchaseDetail, name='purchase'),
    path('purchase/delete/<str:pk>/', purchaseDelete, name='delete-purchase'),

    # sales
    path('sales/', saleTable, name='sales'),
    path('sale/<str:pk>/', saleDetail, name='sale'),
    path('sale/delete/<str:pk>/', saleDelete, name='delete-sale'),

]

transactions/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import (
    DecimalValidator, RegexValidator,
    MaxLengthValidator, validate_integer)

from product.models import Product
from partners.models import Client, Supplier
from src.utils import generate_code


class Transaction(models.Model):
    transaction_id = models.CharField(
        max_length=12, primary_key=True, unique=True,
        validators=[RegexValidator],
        verbose_name='Transaction ID', blank=True
    )
    quantity = models.IntegerField(
        validators=[validate_integer],
        verbose_name='Quantity'
    )
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL,
        null=True, verbose_name='Product'
    )
    note = models.TextField(
        blank=True, null=True,
        validators=[MaxLengthValidator(1000)], 
        verbose_name='Note'
    )
    transaction_date = models.DateField(
        verbose_name='Transaction Date'
    )

    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if self.transaction_id == '':
            self.transaction_id = generate_code()
        if self.created == '':
            self.created = timezone.now
        if self.updated == '':
            self.updated = timezone.now
        
        return super().save(*args, **kwargs)

    class Meta:
        abstract = True
        ordering = ['-transaction_date']


class Sale(Transaction):
    """
    Sale of Products to Clients
    """
    client = models.ForeignKey(
        Client, on_delete=models.SET_NULL,
        null=True, verbose_name='Client', 
        related_name='sales'
    )

    @property
    def final_price(self):
        if self.quantity is None:
            result = 0
            return result
        else:
            result = float(self.quantity) * float(self.product.final_price)
            return round(result, 2)
    
    def __str__(self):
        return f'{self.transaction_id} - {self.quantity} x of product {self.product} at {self.final_price} €'
    

    
class Purchase(Transaction):
    """
    Purchase Products from Suppliers
    """
    supplier = models.ForeignKey(
        Supplier, on_delete=models.SET_NULL,
        null=True, verbose_name='Supplier', 
        related_name='purchases'
    )
    final_price = models.DecimalField(
        max_digits=18, decimal_places=2, default=0.00,
        validators=[DecimalValidator(18, 2)],
        help_text="Value in Euros", verbose_name="Final Price"
    )

    
    def __str__(self):
        return f'{self.transaction_id} - {self.quantity} x of product {self.product} at {self.final_price} €'
    

transactions/forms.py
from django import forms
from transactions.models import Sale, Purchase

class PurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'
        widgets = {
            'transaction_date': forms.DateInput(attrs={'type': 'date'}),
        }
        exclude = ('transaction_id',)


class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = '__all__'
        widgets = {
            'transaction_date': forms.DateInput(attrs={'type': 'date'}),
        }
        exclude = ('transaction_id',)

transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from transactions.models import Purchase, Sale
from transactions.forms import PurchaseForm, SaleForm
from .utils import (add_to_stock, remove_stock, mirrow_modifications_purchase,
                    mirrow_modifications_sale, calc_profit_on_sale)
from src.utils import get_page_obj

@login_required(login_url='authentic:login')
def purchaseTable(request):
    """
    View Purchases,
    Contains a table with all purchases,
    Search on Navbar by: transaction_id, name, note
    Possibility to create new purchase,
    when a new purchase is created the quantity is added to the stock
    by the add_to_stock function
    """

    q = request.GET.get('q') if request.GET.get('q') is not None else ''

    purchases = Purchase.objects.filter(
        Q(transaction_id__icontains=q) |
        Q(product__name__icontains=q) |
        Q(note__icontains=q)
    )
    page_obj = get_page_obj(purchases, request)

    form = PurchaseForm()
    if request.method == 'POST':
        form = PurchaseForm(request.POST)
        if form.is_valid():
            # purchase = form.save()
            
            # add_to_stock(purchase)
            
            messages.success(request, "Purchase Added.")
            return redirect('transactions:purchases')
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'objs' : purchases,
        'form' : form,
        'page_obj' : page_obj,
    }
    return render(request, 'transactions/purchase/table.html', context)

@login_required(login_url='authentic:login')
def purchaseDetail(request, pk):
    """
    Detail view of a purchased transaction,
    Possibility to update purchase,
    Calculation of sale price,
    Calculation of profit with calc_profit_on_sale
    mirrow_modification function deals with the logic behind updating a purchase instance
    """
    purchase = get_object_or_404(Purchase, transaction_id=pk)

    old_purchase_product = purchase.product
    old_purchase_quantity = purchase.quantity


    sold_product_for = round(float(purchase.product.final_price) * float(purchase.quantity), 2)
    profit_on_sale = calc_profit_on_sale(purchase)
    


    form = PurchaseForm(instance=purchase)
    if request.method == 'POST':
        form = PurchaseForm(request.POST, instance=purchase)
        if form.is_valid():
            # new_purchase = form.save(commit=False)

            # mirrow_modifications_purchase(new_purchase, old_purchase_product, old_purchase_quantity)

            # new_purchase.save()
            messages.success(request, "Purchase Updated.")
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'obj' : purchase,
        'form' : form,
        'profit':profit_on_sale,
        'sold_product_for':sold_product_for,
    }
    return render(request, 'transactions/purchase/detail.html', context)

@login_required(login_url='authentic:login')
def purchaseDelete(request, pk):
    """
    Delete Purchase,
    When success the quantity purchased is removed from stock instance
    remove_stock function is called
    """
    purchase = get_object_or_404(Purchase, transaction_id=pk)
    if request.method == 'POST':
        # purchase.delete()
        messages.success(request, f"Purchase {{purchase.transaction_id}} deleted")

        # remove_stock(purchase)

        return redirect('transactions:purchases')
    
    return render(request, 'delete.html', {'obj':purchase})



# Sale
@login_required(login_url='authentic:login')
def saleTable(request):
    """
    View Sales,
    Contains a table with all sales,
    Search on Navbar by: transaction_id, product, note
    Possibility to create new sale,
    when a new sale is created the quantity is removed from the stock
    by the remove_stock function
    """

    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    
    sales = Sale.objects.filter(
        Q(transaction_id__icontains=q) |
        Q(product__name__icontains=q) |
        Q(note__icontains=q)
    )

    page_obj = get_page_obj(sales, request)

    form = SaleForm()
    if request.method == 'POST':
        form = SaleForm(request.POST)
        if form.is_valid():
            # sale = form.save()

            # remove_stock(sale)
            
            messages.success(request, "Created Sale.")
            return redirect('transactions:sales')
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'objs' : sales,
        'form' : form,
        'page_obj' : page_obj,
    }
    return render(request, 'transactions/sale/table.html', context)

@login_required(login_url='authentic:login')
def saleDetail(request, pk):
    """
    Detail view of a sales transaction,
    Possibility to update sale,
    mirrow_modification function deals with the logic behind updating a sale instance
    """
    sale = get_object_or_404(Sale, transaction_id=pk)

    old_sale_product = sale.product
    old_sale_quantity = sale.quantity



    form = SaleForm(instance=sale)
    if request.method == 'POST':
        form = SaleForm(request.POST, instance=sale)
        if form.is_valid():
            # new_sale = form.save(commit=False)
            
            # mirrow_modifications_sale(new_sale, old_sale_product, old_sale_quantity)

            # new_sale.save()
            messages.success(request, "Sale Updated.")
        else:
            messages.error(request, f'{form.errors}')


    context = {
        'obj':sale,
        'form':form,
    }
    return render(request, "transactions/sale/detail.html", context)


@login_required(login_url='authentic:login')
def saleDelete(request, pk):
    """
    Delete sale,
    When success the quantity sale is added to the stock instance
    add_to_stock function is called
    """
    sale = get_object_or_404(Sale, transaction_id=pk)

    if request.method == 'POST':
        # sale.delete()
        
        # add_to_stock(sale)

        messages.success(request, "Sale Deleted.")
        return redirect('transactions:sales')
    return render(request, 'delete.html', {'obj':sale})

transactions/templates/transactions/sale/create-sale-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModal">Create Sale</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body row g-3">
                        {{form|crispy}}
                </div>
                <div class="modal-footer col-12">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Submit<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>

transactions/templates/transactions/sale/detail.html
{% extends 'main.html' %}
{% block title %}- Sale {{obj.transaction_id}} {% endblock title %}
{% block content %}
{% include 'transactions/purchase/update-purchase-modal.html' %}

<main class="content p-2">
  <div class="container-xl">
    <!-- Title + Action -->
    <div class="row">
      <div class="col">
        <h4 class="title">Transaction {{obj.transaction_id}}</h4>
      </div>
      <div class="col">
        <div class="action text-end">
          <button
            type="button"
            class="btn btn-outline-warning"
            data-bs-toggle="modal"
            data-bs-target="#updateModal{{obj.id}}">
            <i class="fa-solid fa-pen-to-square"></i>
          </button>
        </div>
      </div>
    </div>
    <!-- Title + Action End -->
    <hr />
    <!-- client Information Card -->
    <div class="row">
      <div class="col d-flex">
        <div class="card flex-fill border-0 illustration">
          <div class="card-body p-0 d-flex flex-fill">
            <div class="row g-0 w-100">
              <div class="col pt-4">
                <div class="p-3 m-1">
                  <h4 class="mt-2 p-2 text-center">
                    <span class="badge text-bg-danger"
                      >Sale</span
                    >
                    <span class="badge text-bg-warning"
                      >{{obj.product.name}}</span
                    >
                    <span class="badge text-bg-success"
                      >{{obj.product.measurement}}</span
                    >
                    <span class="badge text-bg-secondary"
                      >{{obj.product.category}}</span
                    >
                    <span class="badge text-bg-info"
                      >{{obj.transaction_date}}</span
                    >
                  </h4>
                  <div class="container pt-4">
                    <table
                      class="table table-striped table-bordered border-dark">
                      <thead>
                        <tr class="table-dark text-white text-center">
                          <th scope="col">Client</th>
                          <th scope="col">Type</th>
                          <th scope="col">Quantity</th>
                          <th scope="col">Unit Cost</th>
                          <th scope="col">Sold Price</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr class="text-center">
                          <td>{{obj.client.name}}</td>
                          <td>{{obj.client.entity}}</td>
                          <td><b>{{obj.quantity}}</b></td>
                          <td><b>{{obj.product.final_price}} €</b></td>
                          <td><b>{{obj.final_price}} €</b></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                  <div class="card text-bg-dark mb-3">
                    <div class="card-header">Note:</div>
                    <div class="card-body">
                      <p class="card-text">{{obj.note}}</p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 align-self-center text-end">
                <img
                  src="{{obj.product.product_img.url}}"
                  class="img-fluid illustration-img"
                  alt="{{obj.product.name}} image" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Supplier Information Card -->
  </div>
</main>

{% endblock content %}

transactions/templates/transactions/sale/table.html
{% extends 'main.html' %}
{% block title %}
- Sales
{% endblock title %}

{% block content %}

{% include 'transactions/sale/create-sale-modal.html' %}

<main class="content p-2">
    <div class="container-xl">
        <!-- Title + Action -->
        <div class="row">
            <div class="col">
                <h4 class="title">
                    Sales
                </h4>
            </div>
            <div class="col">
                <div class="action text-end">
                    <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#createModal">
                        <i class="fa-solid fa-folder-plus"></i>
                    </button>
                </div>
            </div>
        </div>
        <!-- End Title + Action -->
        <hr>
      
        <!-- Card with Table -->
         <div class="card border-0">
            <div class="d-flex px-4 py-4">
                <table class="table table-striped table-bordered border-dark">
                    <thead>
                        <tr class="table-dark text-white text-center">
                            <th scope="col">#</th>
                            <th scope="col">Product</th>
                            <th scope="col">Client</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Final Price</th>
                            <th scope="col">Transaction Date</th>
                            <th scope="col">Activity</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in page_obj %}
                        <tr class="text-center">
                            <th scope="row">{{obj.transaction_id}}</th>
                            <th scope="row">{{obj.product.name}}</th>
                            <th scope="row">{{obj.client.name}}</th>
                            <th scope="row">{{obj.quantity}}</th>
                            <th scope="row">{{obj.final_price}} €</th>
                            <th scope="row">{{obj.transaction_date}}</th>
                             <td>
                                <!-- Detail -->
                                <a class="btn btn-sm btn-outline-success" href="{% url 'transactions:sale' obj.transaction_id %}">
                                    <i class="fa-solid fa-eye"></i>
                                </a>
                                <!-- Delete -->
                                <a class="btn btn-sm btn-outline-danger" href="{% url 'transactions:delete-sale' obj.transaction_id %}">
                                    <i class="fa-solid fa-x"></i>
                                </a>
                             </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
         </div>
        <!-- End Card with Table -->
        {% include 'pagination.html' %}
    </div>
</main>
{% endblock content %}

transactions/templates/transactions/sale/update-sale-modal.html
{% load crispy_forms_tags %}
<div class="modal fade" id="updateModal{{obj.id}}" tabindex="-1" aria-labelledby="updateModal{{obj.id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModal{{obj.id}}">Update Sale</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body row g-3">
                    {{form|crispy}}
                </div>
                <div class="modal-footer col-12">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>