dashboard/urls.py
from django.urls import path
from .views import (
    homeView,
)
app_name = 'dashboard'

urlpatterns = [
    path('', homeView, name='home'),
]

partners/urls.py
from django.urls import path
from .views import (
    supplierTable,
    supplierDetail,
    supplierDelete,

    entityTypeTable,
    entityTypeDetail,
    entityTypeDelete,

    clientTable,
    clientDetail,
    clientDelete,
)
app_name = 'partners'

urlpatterns = [
    # suppliers
    path('suppliers/', supplierTable, name='suppliers'),
    path('supplier/<str:pk>/', supplierDetail, name='supplier'),
    path('supplier/delete/<str:pk>', supplierDelete, name='delete-supplier'),

    #entity Type
    path('entity-type/', entityTypeTable, name='entity-types'),
    path('entity-type/<str:pk>/', entityTypeDetail, name='entity-type'),
    path('entity-type/delete/<str:pk>/', entityTypeDelete, name='delete-entity-type'),


    #clients
    path('clients/', clientTable, name='clients'),
    path('client/<str:pk>/', clientDetail, name='client'),
    path('client/delete/<str:pk>/', clientDelete, name='delete-client'),



]

product/urls.py
from django.urls import path
from .views import (
    productTable,
    productDetail,
    productDelete,

    categoryTable,
    categoryDetail,
    categoryDelete,
    
    measurementTable,
    measurementDetail,
    measurementDelete,
)
app_name = 'product'

urlpatterns = [
    # products
    path('', productTable, name='table'),
    path('detail/<str:pk>/', productDetail, name='detail'),
    path('delete/<str:pk>/', productDelete, name='delete'),

    #categories
    path('categories/', categoryTable, name='categories'),
    path('category/<str:pk>/', categoryDetail, name='category'),
    path('category/delete/<str:pk>/', categoryDelete, name='category-delete'),

    #measurement
    path('measurements/', measurementTable, name='measurements'),
    path('measurement/<str:pk>/', measurementDetail, name='measurement'),
    path('measurement/delete/<str:pk>/', measurementDelete, name='measurement-delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from .settings import IS_PRODUCTION

urlpatterns = [
    path('', include('dashboard.urls')),
    path('authentic/', include('authentic.urls')),
    path('product/', include('product.urls')),
    path('stock/', include('stock.urls')),
    path('partners/', include('partners.urls')),
    path('transactions/', include('transactions.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)


if not IS_PRODUCTION:
    urlpatterns += [
        path('gest/admin/', admin.site.urls),
    ]

transactions/urls.py
from django.urls import path
from .views import (
    purchaseTable,
    purchaseDelete,
    purchaseDetail,

    saleTable,
    saleDetail,
    saleDelete,

)
app_name = 'transactions'

urlpatterns = [
    #purchases
    path('purchases/', purchaseTable, name='purchases'),
    path('purchase/<str:pk>/', purchaseDetail, name='purchase'),
    path('purchase/delete/<str:pk>/', purchaseDelete, name='delete-purchase'),

    # sales
    path('sales/', saleTable, name='sales'),
    path('sale/<str:pk>/', saleDetail, name='sale'),
    path('sale/delete/<str:pk>/', saleDelete, name='delete-sale'),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import json


from stock.models import Stock
from .utils import (get_products_count, get_categories_count, 
                    get_clients_count,get_measurements_count, 
                    get_sales_count, get_purchases_count, 
                    get_suppliers_count)
from .kpis import (get_income_of_current_month, top_product,
                   get_expense_of_current_month, get_sales_count_of_current_month,
                   get_purchases_count_of_current_month)

@login_required(login_url='authentic:login')
def homeView(request):

    # Counters for cards
    products_count = get_products_count()
    categories_count = get_categories_count()
    measurements_count = get_measurements_count()
    clients_count = get_clients_count()
    sales_count = get_sales_count()
    purchases_count = get_purchases_count()
    suppliers_count = get_suppliers_count()

    # Stock bar chart
    stocks = list(Stock.objects.values('product__name', 'quantity'))
    stocks_json = json.dumps(stocks)


    # KPI's
    sales_current_month = get_income_of_current_month()
    top1_product = top_product()
    purchases_current_month = get_expense_of_current_month()
    sales_count_current_month = get_sales_count_of_current_month()
    purchases_count_current_month = get_purchases_count_of_current_month




    context = {
        'products_count' : products_count,
        'categories_count' : categories_count,
        'measurements_count' : measurements_count,
        'clients_count' : clients_count,
        'sales_count' : sales_count,
        'purchases_count' : purchases_count,
        'suppliers_count' : suppliers_count,
        'stocks':stocks_json,

        'sales_current_month' : sales_current_month,
        'top_product' : top1_product,
        'purchases_current_month' : purchases_current_month,
        'sales_count_current_month' : sales_count_current_month,
        'purchases_count_current_month' : purchases_count_current_month,
    }
    return render(request, 'dashboard/home.html', context)

dashboard/templates/dashboard/home.html
{% extends 'main.html' %}
{% block title %}
- Dashboard
{% endblock title %}

{% block content %}
<main class="content">
    <div class="container-xl">
        <div class="row w-100 g-0">
          <!-- Sales -->
          <div class="col-md-2 col-sm-6 mb-1 d-flex flex-fill justify-content-center">
            <div class="kpi-card orange">
              <span class="card-value">{{sales_current_month}} €</span>
              <span class="card-text">Total Sales <b>{% now "F" %}</b></span>
              <i class="fas fa-solid fa-hand-holding-dollar icon"></i>
            </div>
          </div>
          <!-- Sales Current Month Count -->
          <div class="col-md-2 col-sm-6 mb-1 d-flex flex-fill justify-content-center">
            <div class="kpi-card grey-dark">
              <span class="card-value">{{sales_count_current_month}}</span>
              <span class="card-text">Sales in <b>{% now "F" %}</b></span>
              <i class="fas fa-comments-dollar icon"></i>
            </div>
          </div>
          <!-- Purchases -->
          <div class="col-md-2 col-sm-6 mb-1 d-flex flex-fill justify-content-center">
            <div class="kpi-card red-gradient">
              <span class="card-value">{{purchases_current_month}} €</span>
              <span class="card-text">Total Purchases <b>{% now "F" %}</b></span>
              <i class="fas fa-solid fa-cart-arrow-down icon"></i>
            </div>
          </div>
          <!-- Purchases Current Month Count -->
          <div class="col-md-2 col-sm-6 mb-1 d-flex flex-fill justify-content-center">
            <div class="kpi-card grey-dark">
              <span class="card-value">{{purchases_count_current_month}}</span>
              <span class="card-text">Purchases in <b>{% now "F" %}</b></span>
              <i class="fas fa-comments-dollar icon"></i>
            </div>
          </div>
          <!-- Top 1 product -->
          <div class="col-md-2 col-sm-6 mb-1 d-flex flex-fill justify-content-center">
            <div class="kpi-card purple">
              <span class="card-value">{{top_product.product__name}}</span>
              <span class="card-text">Top Selling Product</b></span>
              <i class="fas fa-1 icon"></i>
            </div>
          </div>


      </div>
      <div class="row g-0 w-100">
        <!-- Bar Chart -->
        {% include 'stock/bar-chart.html' %}
        <!-- End Bar Chart -->
      </div>
      <div class="row g-0 w-100">
        <!-- Products -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Products</h5>
            <div class="card-body">
              <a href="{% url 'product:table' %}" class="btn btn-outline-warning btn-lg mt-2">{{products_count}}
                <i class="fa-solid fa-box px-2"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Categories -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Categories</h5>
            <div class="card-body">
              <a href="{% url 'product:categories' %}" class="btn btn-outline-warning btn-lg mt-2">{{categories_count}}
                <i class="fa-solid fa-list px-2"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Measurements -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Measurements</h5>
            <div class="card-body">
              <a href="{% url 'product:measurements' %}" class="btn btn-outline-warning btn-lg mt-2">{{measurements_count}}
                <i class="fa-solid fa-ruler px-2"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Clients -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Clients</h5>
            <div class="card-body">
              <a href="{% url 'partners:clients' %}" class="btn btn-outline-warning btn-lg mt-2">{{clients_count}}
                <i class="fa-solid fa-person px-2"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Sales -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Sales</h5>
            <div class="card-body">
              <a href="{% url 'transactions:sales' %}" class="btn btn-outline-warning btn-lg mt-2">{{sales_count}}
                <i class="fa-solid fa-money-bill-trend-up px-2"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Purchases -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Purchases</h5>
            <div class="card-body">
              <a href="{% url 'transactions:purchases' %}" class="btn btn-outline-warning btn-lg mt-2">{{purchases_count}}
                <i class="fa-solid fa-money-check px-2"></i>
              </a>
            </div>
          </div>
        </div>
        <!-- Suppliers -->
        <div class="col-md-3 col-sm-6 mb-2 p-2 d-flex flex-fill justify-content-center">
          <div class="card text-center border-secondary border-1 shadow bg-transparent text-secondary" style="width: 22rem;">
            <h5 class="card-header bg-dark text-white">Suppliers</h5>
            <div class="card-body">
              <a href="{% url 'partners:suppliers' %}" class="btn btn-outline-warning btn-lg mt-2">{{suppliers_count}}
                <i class="fa-solid fa-truck-fast px-2"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
</main>
{% endblock content %}