partners/urls.py
from django.urls import path
from .views import (
    supplierTable,
    supplierDetail,
    supplierDelete,

    entityTypeTable,
    entityTypeDetail,
    entityTypeDelete,

    clientTable,
    clientDetail,
    clientDelete,
)
app_name = 'partners'

urlpatterns = [
    # suppliers
    path('suppliers/', supplierTable, name='suppliers'),
    path('supplier/<str:pk>/', supplierDetail, name='supplier'),
    path('supplier/delete/<str:pk>', supplierDelete, name='delete-supplier'),

    #entity Type
    path('entity-type/', entityTypeTable, name='entity-types'),
    path('entity-type/<str:pk>/', entityTypeDetail, name='entity-type'),
    path('entity-type/delete/<str:pk>/', entityTypeDelete, name='delete-entity-type'),


    #clients
    path('clients/', clientTable, name='clients'),
    path('client/<str:pk>/', clientDetail, name='client'),
    path('client/delete/<str:pk>/', clientDelete, name='delete-client'),



]

product/urls.py
from django.urls import path
from .views import (
    productTable,
    productDetail,
    productDelete,

    categoryTable,
    categoryDetail,
    categoryDelete,
    
    measurementTable,
    measurementDetail,
    measurementDelete,
)
app_name = 'product'

urlpatterns = [
    # products
    path('', productTable, name='table'),
    path('detail/<str:pk>/', productDetail, name='detail'),
    path('delete/<str:pk>/', productDelete, name='delete'),

    #categories
    path('categories/', categoryTable, name='categories'),
    path('category/<str:pk>/', categoryDetail, name='category'),
    path('category/delete/<str:pk>/', categoryDelete, name='category-delete'),

    #measurement
    path('measurements/', measurementTable, name='measurements'),
    path('measurement/<str:pk>/', measurementDetail, name='measurement'),
    path('measurement/delete/<str:pk>/', measurementDelete, name='measurement-delete'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf import settings
from django.conf.urls.static import static
from .settings import IS_PRODUCTION

urlpatterns = [
    path('', include('dashboard.urls')),
    path('authentic/', include('authentic.urls')),
    path('product/', include('product.urls')),
    path('stock/', include('stock.urls')),
    path('partners/', include('partners.urls')),
    path('transactions/', include('transactions.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)


if not IS_PRODUCTION:
    urlpatterns += [
        path('gest/admin/', admin.site.urls),
    ]

transactions/urls.py
from django.urls import path
from .views import (
    purchaseTable,
    purchaseDelete,
    purchaseDetail,

    saleTable,
    saleDetail,
    saleDelete,

)
app_name = 'transactions'

urlpatterns = [
    #purchases
    path('purchases/', purchaseTable, name='purchases'),
    path('purchase/<str:pk>/', purchaseDetail, name='purchase'),
    path('purchase/delete/<str:pk>/', purchaseDelete, name='delete-purchase'),

    # sales
    path('sales/', saleTable, name='sales'),
    path('sale/<str:pk>/', saleDetail, name='sale'),
    path('sale/delete/<str:pk>/', saleDelete, name='delete-sale'),

]

partners/models.py
from django.db import models
from django.core.validators import (
    EmailValidator, MinLengthValidator, 
    MaxLengthValidator, RegexValidator,
    validate_image_file_extension)


from product.models import Product
from src.utils import generate_code
from src.validators import validate_names


class EntityType(models.Model):
    """
    Some types of entity like:
    individual, corporate,
    Manufator, Distributor, ....
    """
    entity_type = models.CharField(
        max_length=20, unique=True,
        validators=[validate_names],
        verbose_name='Entity Type'
    )

    def get_clients_count(self):
        return self.clients.count()
    def get_suppliers_count(self):
        return self.suppliers.count()
    
    def __str__(self):
        return f'{self.entity_type}'
    
    class Meta:
        ordering = ['id']


class Partner(models.Model):
    name = models.CharField(
        max_length=255, unique=True,
        validators=[validate_names],
        verbose_name='Name'
    )
    email = models.EmailField(
        blank=True, null=True,
        validators=[EmailValidator], 
        verbose_name='Email'
    )
    contact = models.CharField(
        max_length=20, blank=True, null=True,
        validators=[MinLengthValidator(9), MaxLengthValidator(13)], 
        verbose_name='Phone Number'
    )
    address = models.TextField(
        blank=True, null=True,
        validators=[MaxLengthValidator(300)],
        verbose_name='Address'
    )
    note = models.TextField(
        blank=True, null=True,
        verbose_name='Note'
    )
    active = models.BooleanField(
        default=False, 
        verbose_name='Active'
    )
    partner_logo = models.ImageField(
        upload_to='partner', default='default_img.jpg',
        validators=[validate_image_file_extension],
        verbose_name='Partner Logo', blank=True
    )

    partner_since = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Client(Partner):
    client_id = models.CharField(
        max_length=20, blank=True,
        validators=[RegexValidator],
        verbose_name='Cient ID'
    )
    entity = models.ForeignKey(
        EntityType, on_delete=models.PROTECT,
        null=True, blank=True, verbose_name='Entity Type',
        related_name='clients'
    )

    def save(self, *args, **kwargs):
        if self.client_id == '':
            self.client_id = generate_code()

        return super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.name} ({self.entity})'
    
    class Meta:
        ordering = ['id']


class Supplier(Partner):
    supplier_id = models.CharField(
        max_length=20, blank=True,
        validators=[RegexValidator], 
        verbose_name='Supplier ID'
    )
    products = models.ManyToManyField(
        Product, verbose_name='Products',
        related_name='suppliers'
    )
    entity = models.ForeignKey(
        EntityType, on_delete=models.PROTECT,
        null=True, blank=True, verbose_name='Entity Type', 
        related_name='suppliers'
    )

    def save(self, *args, **kwargs):
        if self.supplier_id == '':
            self.supplier_id = generate_code()

        return super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.name} ({self.entity})'

    class Meta:
        ordering = ['id']

partners/forms.py
from django import forms

from .models import Supplier, Client, EntityType


class SupplierForm(forms.ModelForm):
    name = forms.CharField()
    class Meta:
        model = Supplier
        fields = '__all__'
        exclude = ('supplier_id',)


class ClientForm(forms.ModelForm):
    name = forms.CharField()
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('client_id',)

class EntityTypeForm(forms.ModelForm):
    class Meta:
        model = EntityType
        fields = '__all__'

partners/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


from src.utils import get_page_obj
from .models import Supplier, Client, EntityType
from .forms import SupplierForm, ClientForm, EntityTypeForm
from .utils import get_sales_by_client, get_purchases_by_supplier

# Suppliers
@login_required(login_url='authentic:login')
def supplierTable(request):
    """
    View Suppliers,
    Contains a table with all existing Suppliers,
    Possibility to create new Supplier
    Search on Navbar by: name, email, contact, address, note, entity.
    """
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    
    supplier = Supplier.objects.filter(
        Q(name__icontains=q) |
        Q(email__icontains=q) |
        Q(contact__icontains=q) |
        Q(address__icontains=q) |
        Q(note__icontains=q) |
        Q(entity__entity_type__icontains=q)
    )

    page_obj = get_page_obj(supplier, request)

    form = SupplierForm()
    if request.method == 'POST':
        form = SupplierForm(request.POST)
        if form.is_valid():
            # form.save()
            messages.success(request, "Supplier Created!")
            return redirect('partners:suppliers')
        else:
            messages.error(request, form.errors)

    context = {
        'objs' : supplier,
        'form' : form,
        'page_obj' : page_obj,
    }
    return render(request, 'partners/supplier/table.html', context)

@login_required(login_url='authentic:login')
def supplierDetail(request, pk):
    """
    Detail view of Supplier,
    Possibility to update supplier
    """
    supplier = get_object_or_404(Supplier, id=pk)

    purchases = get_purchases_by_supplier(supplier)

    form = SupplierForm(instance=supplier)
    if request.method == 'POST':
        form = SupplierForm(request.POST, instance=supplier)
        if form.is_valid():
            # form.save()
            messages.success(request, f"Supplier {supplier.name} updated!")
            return redirect('partners:suppliers')
        else:
            messages.error(request, form.errors)
    context = {
        'obj' : supplier,
        'form' : form,
        'purchases': purchases,
    }
    return render(request, 'partners/supplier/detail.html', context)

@login_required(login_url='authentic:login')
def supplierDelete(request, pk):
    """
    Delete a Supplier.
    """
    supplier = get_object_or_404(Supplier, id=pk)
    if request.method == 'POST':
        # supplier.delete()
        messages.success(request, f"Supplier {supplier.name} deleted!")
    return render(request, 'delete.html', {'obj':supplier})

# EntityType
@login_required(login_url='authentic:login')
def entityTypeTable(request):
    """
    View Entity Types,
    Contains a table with all existing Types of Entities,
    Possibility to create new Entity Type
    Search on Navbar by: entity_type
    """
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    entities = EntityType.objects.filter(
        Q(entity_type__icontains=q)
    )

    page_obj = get_page_obj(entities, request)

    form = EntityTypeForm()
    if request.method == 'POST':
        form = EntityTypeForm(request.POST, request.FILES)
        if form.is_valid():
            # form.save()
            messages.success(request, f'Created new Entity Type!')
            return redirect('partners:entity-types')
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'objs' : entities,
        'form' : form,
        'page_obj' : page_obj,
    }
    return render(request, 'partners/entityType/table.html', context)

@login_required(login_url='authentic:login')
def entityTypeDetail(request, pk):
    """
    Detail view of Entity Type,
    Possibility to update type of entity
    """    
    entity = get_object_or_404(EntityType, id=pk)
    suppliers = Supplier.objects.filter(entity=entity)
    # TODO -> ADD CLIENTS TO DISPLAY ON Detail View

    
    form = EntityTypeForm(instance=entity)
    if request.method == 'POST':
        form = EntityTypeForm(request.POST, request.FILES, instance=entity)
        if form.is_valid():
            # form.save()
            messages.success(request, "Supplier Type Updated!")
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'obj': entity,
        'suppliers':suppliers,
        'form':form,
    }
    return render(request, 'partners/entityType/detail.html', context)

@login_required(login_url='authentic:login')
def entityTypeDelete(request, pk):
    """
    Delete Entity Type
    """
    entity = get_object_or_404(EntityType, id=pk)
    if request.method == 'POST':
        # entity.delete()
        messages.success(request, f' Deleted {entity}')
        return redirect('partners:entity-types')
    return render(request, 'delete.html', {'obj':entity})


# Clients
@login_required(login_url='authentic:login')
def clientTable(request):
    """
    View Clients,
    Contains a table with all existing Clients,
    Possibility to create new Client
    Search on Navbar by: name, email, contact, address, note, entity
    """
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    clients = Client.objects.filter(
        Q(name__icontains=q) |
        Q(email__icontains=q) |
        Q(contact__icontains=q) |
        Q(address__icontains=q) |
        Q(note__icontains=q) |
        Q(entity__entity_type__icontains=q)
    )

    page_obj = get_page_obj(clients, request)

    form = ClientForm()
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES)
        if form.is_valid():
            # form = form.save()
            messages.success(request, f'Client {form.name} Created!')
            return redirect('partners:clients')
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'objs' : clients,
        'form' : form,
        'page_obj' : page_obj,
    }
    return render(request, 'partners/client/table.html', context)

@login_required(login_url='authentic:login')
def clientDetail(request, pk):
    """
    Detail view of Client,
    Possibility to update client
    """
    client = get_object_or_404(Client, id=pk)

    sales_by_client = get_sales_by_client(client)

    form = ClientForm(instance=client)
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=client)
        if form.is_valid():
            # form.save()
            messages.success(request, f'Client {client.name} Updated!')
            return redirect('partners:client', client.id)
        else:
            messages.error(request, f'{form.errors}')

    context = {
        'obj' : client,
        'form' : form,
        'sales' : sales_by_client,
    }
    return render(request, 'partners/client/detail.html', context)

@login_required(login_url='authentic:login')
def clientDelete(request, pk):
    """
    Delete Client.
    """
    client = get_object_or_404(Client, id=pk)
    if request.method == 'POST':
        # client.delete()
        messages.success(request, f'{client.name} deleted!')
        return redirect('partners:clients')

    return render(request, 'delete.html', {'obj':client})

partners/templates/partners/supplier/create-supplier-modal.html
{% load crispy_forms_tags %}

<div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="createModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createModal">Create Supplier</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body row g-3">
                        {{form|crispy}}
                </div>
                <div class="modal-footer col-12">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Submit<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>

partners/templates/partners/supplier/detail.html
{% extends 'main.html' %}
{% block title %}- Supplier {{obj.name}} {% endblock title %}

{% block content %}

{% include 'partners/supplier/update-supplier-modal.html' %}

<main class="content p-2">
    <div class="container-fluid">
        <!-- Title + Action -->
        <div class="row">
            <div class="col">
                <h4 class="title">
                    {{obj.name}}
                </h4>
            </div>
            <div class="col">
                <div class="action text-end">
                    <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#updateModal{{obj.id}}">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </button>
                </div>
            </div>
        </div>
        <!-- Title + Action End -->
        <hr>
        <!-- Supplier Information Card -->
        <div class="row">
            <div class="col d-flex">
                <div class="card flex-fill border-0 illustration">
                    <div class="card-body p-0 d-flex flex-fill">
                        <div class="row g-0 w-100">
                            <div class="col pt-4">
                                <div class="p-3 m-1">
                                    <h4 class="mt-2 p-2 text-center">
                                        <span class="badge text-bg-danger">Supplier</span>
                                        <span class="badge text-bg-secondary">{{obj.entity}}</span>
                                        <span class="badge text-bg-info">{{obj.partner_since | timesince}}</span>
                                        {% if obj.active == True %}
                                        <span class="badge text-bg-success">Active</span>
                                        {% else %}
                                        <span class="badge text-bg-danger">Inactive</span>
                                        {% endif %}
                                    </h4>
                                        <div class="container pt-4">
                                            <table class="table table-striped table-bordered border-dark">
                                                <thead>
                                                    <tr class="table-dark text-white text-center">
    
                                                        <th scope="col">Email</th>
                                                        <th scope="col">Contact</th>
                                                        <th scope="col">Address</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr class="text-center">
                                                        <td>{{obj.email}}</td>
                                                        <td>{{ obj.contact|default:"Not Added" }}</td>
                                                        <td><b>{{obj.address|default:"Not Added" }}</b></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="card text-bg-dark mb-3">
                                            <div class="card-header">Note:</div>
                                            <div class="card-body">
                                              <p class="card-text">{{obj.note}}</p>
                                            </div>
                                        </div>                                                                  
                                </div>
                            </div>
                            <div class="col-md-4 align-self-center text-end">
                                <img src="{{obj.partner_logo.url}}" class="img-fluid illustration-img" alt="{{obj.name}} image">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Supplier Information Card -->

        <!-- Purchases Made -->
         {% include 'partners/supplier/purchases-transactions.html' %}
    </div>
</main>

{% endblock content %}

partners/templates/partners/supplier/purchases-transactions.html
<div class="row mt-2">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title mb-2 text-muted">
                    Transactions (Purchases)
                </h5>
                <hr>
                <ul class="list-group">
                    {% for purchase in purchases %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a class="text-decoration-none text-secondary" href="{% url 'product:detail' purchase.product.id %}">{{purchase.product.name}} | </a>
                                <a class="text-decoration-none text-success" href="{% url 'transactions:purchase' purchase.transaction_id %}">{{purchase.transaction_id}}</a>
                            </div>
                            <small class="text-muted">{{purchase.transaction_date}}</small>
                            
                        </div>
                        <span class="badge bg-success rounded-pill mx-2">{{purchase.quantity}}{{purchase.product.measurement}}</span>
                        <span class="badge bg-secondary rounded-pill mx-2">{{purchase.final_price}} €</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

partners/templates/partners/supplier/table.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
{% block title %} - Supplier Info {% endblock title %}
{% block content %}
{% include 'partners/supplier/create-supplier-modal.html' %}

<main class="content p-2">
  <div class="container-fluid">
    <!-- Title + Action -->
    <div class="row">
      <div class="col">
        <h4 class="title">Supplier Information</h4>
      </div>
      <div class="col">
        <div class="action text-end">
          <button
            type="button"
            class="btn btn-outline-warning"
            data-bs-toggle="modal"
            data-bs-target="#createModal">
            <i class="fa-solid fa-folder-plus"></i>
          </button>
        </div>
      </div>
    </div>
    <!-- Title + Action End -->
    <hr />
    <!-- Card with Table -->
    <div class="card border-0">
      <div class="d-flex px-4 py-4">
        <table class="table table-striped table-bordered border-dark">
          <thead>
            <tr class="table-dark text-white text-center">
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Entity</th>
              <th scope="col">Active</th>
              <th scope="col">Email</th>
              <th scope="col">Contact</th>
              <th scope="col">Activity</th>
            </tr>
          </thead>
          <tbody>
            {% for obj in page_obj %}
            <tr class="text-center">
              <th scope="row">{{obj.id}}</th>
              <th scope="row">{{obj.name}}</th>
              <th scope="row">{{obj.entity}}</th>
              <th scope="row">
                {% if obj.active %}
                <span class="badge rounded-pill bg-success">
                    <i class="fa-regular fa-circle-check"></i>
                </span>
                {% else %}
                <span class="badge rounded-pill bg-danger">
                    <i class="fa-regular fa-circle-xmark"></i>
                </span>
                {% endif %}
                </th>
              <th scope="row">{{obj.email}}</th>
              <th scope="row">{{obj.contact}}</th>
              <td>
                <!-- Detail -->
                <a
                  class="btn btn-sm btn-outline-success"
                  href="{% url 'partners:supplier' obj.id %}">
                  <i class="fa-solid fa-eye"></i>
                </a>
                <!-- Delete -->
                <a
                  class="btn btn-sm btn-outline-danger"
                  href="{% url 'partners:delete-supplier' obj.id %}">
                  <i class="fa-solid fa-x"></i>
                </a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <!-- End Card with Table -->
     {% include 'pagination.html' %}
  </div>
</main>
{% endblock content %}

partners/templates/partners/supplier/update-supplier-modal.html
{% load crispy_forms_tags %}
<div class="modal fade" id="updateModal{{obj.id}}" tabindex="-1" aria-labelledby="updateModal{{obj.id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModal{{obj.id}}">Update Supplier</h5>
                <button type="button" class="btn btn-warning" data-bs-dismiss="modal" aria-label="Close"><i
                        class="fa-solid fa-xmark"></i></button>
            </div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body row g-3">
                    {{form|crispy}}
                </div>
                <div class="modal-footer col-12">
                    <button type="submit" class="btn btn-warning border-2 text-bottom p-2">Confirmar<span
                            class="badge bg-dark mx-2"><i class="fa-solid fa-check"></i></span></button>
                </div>
            </form>
        </div>
    </div>
</div>